version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-server-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api-docs"]
      interval: 30s
      timeout: 10s
      retries: 3
