version: "3.8"

services:
  api:
    environment:
      - NODE_ENV=production
      - PORT=8000
    restart: always
    command: npm run start:prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api-docs"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s